# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37ec749c059fd0c17d23772bb4db405445b04572045b15618480c026dad1131a5ecd1e878ca3abc12182f7eaca36b6a3c67e8b6d67f73adf5160e852be88a6cc

test:
  secret_key_base: 05fb3dc9113ff15a38f217135da819b5e840bb20f45230703faed533cfa29c3249e046496fe4a8eb80a15d6ad7bd6b9ea3157ccb587b7f94ac8edbd6f18715f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
